#!/usr/bin/env python3

import os
import sys
import time
import struct
import argparse
import numpy as np
from tqdm import tqdm


class Zeus2Polaris:
	""" """
	def __init__(self, nframe, output_grid, verbose=False):
		self.nframe = str(nframe).zfill(5)
		self.output_grid = output_grid
		self.verbose = verbose
		self.IDs = list()
		self.fields = list()
		self.nghost = 0
		self.id_grid = 30
		self.dust_gas_mass_ratio = 0.01
		self._print(f'Creating spherical polaris grid for frame: {self.nframe}')

	def _print(self, string):
		"""Customized print function to work only when verbose mode is enabled."""
		if self.verbose:
			print(f'[{self.__class__.__name__}] {string}')

	def add_quantity(self, ID, infile, name=''):
		"""Add a quantity to the list of quantities to be written into 
			the polaris grid."""

		self._print(f'Adding field: {name}')
		self.IDs.append(ID)

		# Read physical quantity
		self.field = self._read_data(f"{infile}{self.nframe}", trim_ghosts=self.nghost, shape=self.shape)

		# If gas density
		if ID in [28]:
			# Check if constant density is desired
			if self.constant_density > 0:
				self._print(f'Setting gas density to a constant value: {self.constant_density} (g/cm^-3)')
				self.field = np.full(self.field.shape, self.constant_density)

		# If dust density
		if ID in [1, 29]:
			# Check if constant density is desired
			if self.constant_density > 0:
				rescaled_const_dens = self.constant_density * self.dust_gas_mass_ratio
				self._print(f'Setting dust density to a constant value: {rescaled_const_dens} (g/cm^-3)')
				self.field = np.full(self.field.shape, rescaled_const_dens)

			# rescale by the dust-to-gas mass ratio
			self.field *= self.dust_gas_mass_ratio

		# If magnetic field component
		if ID in [4, 5, 6]:
			# Convert from Lorentz-Heaviside to Gaussian (CGS) unit system
			self.field *= np.sqrt(4*np.pi)

		# If velocity field component
		if ID in [7, 8, 9]:
			# Set null velocities to a low value to avoid problems within polaris
			minvel =  1e-5
			self.field = np.where(self.field != 0.0, self.field, minvel)

		# Add the current field to the list of fields to be written
		self.fields.append(self.field)
	
	def set_cell_edges(self, r, theta, phi):
		"""Set the cell edges to be written into the head of the grid."""

		self._print(f'Setting cell edges')
		# Read grid cell edges
		self.r_e = self._read_data(r, trim_ghosts=self.nghost)
		self.th_e = self._read_data(theta, trim_ghosts=self.nghost)
		self.ph_e = self._read_data(phi, trim_ghosts=self.nghost)

		# Grid Dimension
		self.dr = np.diff(self.r_e)
		self.dth = np.diff(self.th_e)
		self.dph = np.diff(self.ph_e)
		self.n_r = self.r_e.size
		self.n_th = self.th_e.size
		self.n_ph = self.ph_e.size
		self.n_cells = (self.n_r * self.n_th * self.n_ph)
		self.shape = (self.n_r+2*self.nghost, \
					self.n_ph+2*self.nghost, \
					self.n_th+2*self.nghost)
		self.mu = 2.36
		self.mu_CO = 28.01
		self.m_H = 1.67355751e-24 # [g]

	def set_fr(self, fr):
		self.f_r = fr
	
	def set_fphi(self, fphi):
		self.f_ph = fphi

	def set_ftheta(self, ftheta):
		self.f_th = ftheta

	def _read_data(self, filename, shape=None, unshape=True, trim_ghosts=None, entries=-1):
		"""Read data from the zeusTW files. """
		# Check file existence
		if not os.path.isfile(filename):
			raise IOError(f"{filename} does not exists or cannot be read.")

		# Read file in binary format
		with open(filename, 'rb') as binfile:
			self.data = np.fromfile(file=binfile, dtype=np.double, count=entries)	

			# Trim ghost cells if required
			if trim_ghosts is not None:
				trim_ghosts = int(trim_ghosts)
				if shape is not None:
					self.data = self.data.reshape(shape, order='F')

					self.data = self.data[trim_ghosts:-trim_ghosts,\
										trim_ghosts:-trim_ghosts,\
										trim_ghosts:-trim_ghosts]
				else:
					self.data = self.data[trim_ghosts:-trim_ghosts]

			# Turn back to 1D
			if unshape:
				if self.data.ndim > 1:
					self.data = np.swapaxes(self.data, 1, 2)

				self.data = np.ravel(self.data)

		return self.data

	def _write_data(self, dtype, var, endl=False):
		""" Write data into the new polaris grid."""
		if self.format_ == 'binary':
			self.file_.write(struct.pack(dtype, var))

		elif self.format_ == 'ascii':
			string = f'{var}\n' if endl else f'{var} '
			self.file_.write(string)

	def create_grid(self, format_='binary'):
		"""Write all the data into the output grid in POLARIS format."""

		self.start = time.time()

		# Define output format
		self.format_ = format_
		if self.format_ == 'binary':
			self.output_grid += f"_{self.nframe}.dat"
			self.file_ = open(self.output_grid, "wb")

		elif self.format_ == 'ascii':
			self.output_grid += f"_{self.nframe}.txt"
			self.file_ = open(self.output_grid, "w")

		else:
			raise ValueError('self.format_ must be either "binary" or "ascii".')				

		self._print(f"Writing to file: {self.output_grid}")

		# Write the header
		# Note:	"H": format string for unsigned short
		# 		"d": format string for double
		self._write_data("H", self.id_grid, endl=True)
		self._write_data("H", len(self.IDs), endl=True)

		# Write the IDs of phys. quantities
		[self._write_data("H", i, endl=True) for i in self.IDs]

		# Write grid parameters
		# NOTE: the original grid is uniform in phi but not in r and theta
		self._write_data("d", self.r_e[0])
		self._write_data("d", self._read_data('z_x1ap')[-self.nghost] , endl=True)
		self._write_data("H", self.n_r)
		self._write_data("H", self.n_th)
		self._write_data("H", self.n_ph, endl=True)

		# Write the shape parameters f_r, f_theta and f_phi 
		self._write_data("d", self.f_r, endl=True)   
		self._write_data("d", self.f_ph, endl=True)  
		self._write_data("d", self.f_th, endl=True)  

		# Write the cell borders in the r, phi and theta direction
		for r in self.r_e[1:]:
			self._write_data("d", r)	
		if self.format_ == 'ascii':
			self._write_data("d", '', endl=True)

		for phi in self.ph_e[1:]:
			self._write_data("d", phi)
		if self.format_ == 'ascii':
			self._write_data("d", '', endl=True)

		for theta in self.th_e[1:]:
			self._write_data("d", theta)	
		if self.format_ == 'ascii':
			self._write_data("d", '', endl=True)

		# Write physical data: first iterate over cells
		for cell in tqdm(range(self.n_cells)) if (self.verbose and not self.no_pb) else range(self.n_cells):
			# Then iterate over fields
			for (j, field) in enumerate(self.fields):
				self._write_data("d", field[cell], endl=True if j+1 == len(self.IDs) else False)

		# Set the central cell to zero in all quantities.
		for (j, field) in enumerate(self.fields):
			self._write_data("d", 0, endl=True if j+1 == len(self.IDs) else False)
		
		self.file_.close()	
		
		self.runtime = time.time()-self.start
		self._print(f'Elapsed time: {time.strftime("%H:%M:%S",time.gmtime(self.runtime))}')



if __name__ == "__main__":

	# Initialize the argument parser
	parser = argparse.ArgumentParser(prog='zeus2polaris',
									description='Convert from ZeusTW dumpfiles into a POLARIS binary grid')

	# Define command line options
	parser.add_argument('nframe', action='store', \
						help='Frame number by which all input files are suffixed.')

	parser.add_argument('-o', '--output', action='store', default='polaris_grid/lmd2.4-1k-Slw', \
						help='Name of the output grid. It will suffixed by the frame number')

	parser.add_argument('-f', '--format', action='store', choices=['binary','ascii'], default='binary', \
						help='Format of the output grid. POLARIS uses binary but ascii is useful to check the grid.')

	parser.add_argument('--constant-density', action='store', type=float, default=0, \
						help='Option to create a constant density grid by replacing the density field with a given number and keeping the grid structure.')

	parser.add_argument('--no-progress-bar', action='store_true', \
						help='Disables the printing of a progress bar to standard output in verbose mode.')

	parser.add_argument('-v', '--verbose', action='store_true')

	cli = parser.parse_args()

	# Create a converter instance
	grid = Zeus2Polaris(nframe=cli.nframe, output_grid=cli.output, verbose=cli.verbose)
	
	# Set the number of ghost cells
	grid.nghost = 3

	# Set the files containing the cell edges
	grid.set_cell_edges(r='z_x1ap', theta='z_x2ap', phi='z_x3ap')

	# Set the coordinate shape parameters
	grid.set_fr(0)
	grid.set_fphi(0)
	grid.set_ftheta(0)

	grid.dust_gas_mass_ratio = 0.01
	
	# Set constant density property if it was entered
	grid.constant_density = cli.constant_density

	# Add quantities to include in the output grid.
	grid.add_quantity(ID=28, infile='o_d__', name='gass mass density')
	grid.add_quantity(ID=29, infile='o_d__', name='dust mass density')
	grid.add_quantity(ID=4, infile='o_b1_', name='magnetic field in x-direction')
	grid.add_quantity(ID=5, infile='o_b2_', name='magnetic field in y-direction')
	grid.add_quantity(ID=6, infile='o_b3_', name='magnetic field in z-direction')
	grid.add_quantity(ID=7, infile='o_v1_', name='gas velocity in x-direction') 
	grid.add_quantity(ID=8, infile='o_v2_', name='gas velocity in y-direction') 
	grid.add_quantity(ID=9, infile='o_v3_', name='gas velocity in z-direction') 

	# Enable/disable the usage of a progress bar
	grid.no_pb = cli.no_progress_bar

	# Create the grid
	grid.create_grid(format_=cli.format)

